// write a JSON file which exports an array of 100 objects. Each object contains four properties- city: which is the city name,  state: which is the name of the state which the city is in, latitude: which is the location's latitude, longitude: which is the locations longitude.  Only include locations in India.

module.exports = [
    {
        city: "Mumbai",
        state: "Maharashtra",
        latitude: 19.076,
        longitude: 72.8777,
    },
    {
        city: "Delhi",
        state: "Delhi",
        latitude: 28.6139,
        longitude: 77.209,
    },
    {
        city: "Bangalore",
        state: "Karnataka",
        latitude: 12.9716,
        longitude: 77.5946,
    },
    {
        city: "Kolkata",
        state: "West Bengal",
        latitude: 22.5726,
        longitude: 88.3639,
    },
    {
        city: "Chennai",
        state: "Tamil Nadu",
        latitude: 13.0827,
        longitude: 80.2707,
    },
    {
        city: "Hyderabad",
        state: "Telangana",
        latitude: 17.385,
        longitude: 78.4867,
    },
    {
        city: "Pune",
        state: "Maharashtra",
        latitude: 18.5204,
        longitude: 73.8567,
    },
    {
        city: "Ahmedabad",
        state: "Gujarat",
        latitude: 23.0225,
        longitude: 72.5714,
    },
    {
        city: "Jaipur",
        state: "Rajasthan",
        latitude: 26.9124,
        longitude: 75.7873,
    },
    {
        city: "Lucknow",
        state: "Uttar Pradesh",
        latitude: 26.8467,
        longitude: 80.9462,
    },
    {
        city: "Kanpur",
        state: "Uttar Pradesh",
        latitude: 26.4499,
        longitude: 80.3319,
    },
    {
        city: "Nagpur",
        state: "Maharashtra",
        latitude: 21.1458,
        longitude: 79.0882,
    },
    {
        city: "Indore",
        state: "Madhya Pradesh",
        latitude: 22.7196,
        longitude: 75.8577,
    },
    {
        city: "Thane",
        state: "Maharashtra",
        latitude: 19.2183,
        longitude: 72.9781,
    },
    {
        city: "Bhopal",
        state: "Madhya Pradesh",
        latitude: 23.2599,
        longitude: 77.4126,
    },
    {
        city: "Visakhapatnam",
        state: "Andhra Pradesh",
        latitude: 17.6868,
        longitude: 83.2185,
    },
    {
        city: "Pimpri-Chinchwad",
        state: "Maharashtra",
        latitude: 18.6279,
        longitude: 73.8001,
    },
    {
        city: "Patna",
        state: "Bihar",
        latitude: 25.5941,
        longitude: 85.1376,
    },
    {
        city: "Vadodara",
        state: "Gujarat",
        latitude: 22.3072,
        longitude: 73.1812,
    },
    {
        city: "Ludhiana",
        state: "Punjab",
        latitude: 30.901,
        longitude: 75.8573,
    },
    {
        city: "Agra",
        state: "Uttar Pradesh",
        latitude: 27.1767,
        longitude: 78.0081,
    },
    {
        city: "Nashik",
        state: "Maharashtra",
        latitude: 20.5937,
        longitude: 78.9629,
    },
    {
        city: "Faridabad",
        state: "Haryana",
        latitude: 28.4089,
        longitude: 77.3178,
    },
    {
        city: "Meerut",
        state: "Uttar Pradesh",
        latitude: 28.6139,
        longitude: 77.209,
    },
    {
        city: "Rajkot",
        state: "Gujarat",
        latitude: 22.3039,
        longitude: 70.8022,
    },
    {
        city: "Kalyan-Dombivali",
        state: "Maharashtra",
        latitude: 19.2719,
        longitude: 73.1213,
    },
    {
        city: "Vasai-Virar",
        state: "Maharashtra",
        latitude: 19.3919,
        longitude: 72.8397,
    },
    {
        city: "Varanasi",
        state: "Uttar Pradesh",
        latitude: 25.3176,
        longitude: 82.9739,
    },
    {
        city: "Srinagar",
        state: "Jammu and Kashmir",
        latitude: 34.0836,
        longitude: 74.7973,
    },
    {
        city: "Aurangabad",
        state: "Maharashtra",
        latitude: 19.8762,
        longitude: 75.3433,
    },
    {
        city: "Dhanbad",
        state: "Jharkhand",
        latitude: 23.7957,
        longitude: 86.4304,
    },
    {
        city: "Amritsar",
        state: "Punjab",
        latitude: 31.634,
        longitude: 74.8748,
    },
    {
        city: "Navi Mumbai",
        state: "Maharashtra",
        latitude: 19.033,
        longitude: 73.0297,
    },
    {
        city: "Allahabad",
        state: "Uttar Pradesh",
        latitude: 25.4358,
        longitude: 81.8463,
    },
    {
        city: "Howrah",
        state: "West Bengal",
        latitude: 22.5958,
        longitude: 88.2636,
    },
    {
        city: "Ranchi",
        state: "Jharkhand",
        latitude: 23.3441,
        longitude: 85.3096,
    },
    {
        city: "Gwalior",
        state: "Madhya Pradesh",
        latitude: 26.2183,
        longitude: 78.1828,
    },
    {
        city: "Jabalpur",
        state: "Madhya Pradesh",
        latitude: 23.1815,
        longitude: 79.9864,
    },
    {
        city: "Coimbatore",
        state: "Tamil Nadu",
        latitude: 11.0168,
        longitude: 76.9558,
    },
    {
        city: "Vijayawada",
        state: "Andhra Pradesh",
        latitude: 16.5062,
        longitude: 80.648,
    },
    {
        city: "Jodhpur",
        state: "Rajasthan",
        latitude: 26.2389,
        longitude: 73.0243,
    },
    {
        city: "Madurai",
        state: "Tamil Nadu",
        latitude: 9.9252,
        longitude: 78.1198,
    },
    {
        city: "Raipur",
        state: "Chhattisgarh",
        latitude: 21.2514,
        longitude: 81.6296,
    },
    {
        city: "Kota",
        state: "Rajasthan",
        latitude: 25.2138,
        longitude: 75.8648,
    },
    {
        city: "Chandrapur",
        state: "Maharashtra",
        latitude: 19.9703,
        longitude: 79.3032,
    },
    {
        city: "Guwahati",
        state: "Assam",
        latitude: 26.1445,
        longitude: 91.7362,
    },
    {
        city: "Solapur",
        state: "Maharashtra",
        latitude: 17.6599,
        longitude: 75.9064,
    },
    {
        city: "Hubli-Dharwad",
        state: "Karnataka",
        latitude: 15.3647,
        longitude: 75.124,
    },
    {
        city: "Tiruchirappalli",
        state: "Tamil Nadu",
        latitude: 10.7905,
        longitude: 78.7047,
    },
    {
        city: "Bareilly",
        state: "Uttar Pradesh",
        latitude: 28.367,
        longitude: 79.4304,
    },
    {
        city: "Mysore",
        state: "Karnataka",
        latitude: 12.2958,
        longitude: 76.6394,
    },
    {
        city: "Tiruppur",
        state: "Tamil Nadu",
        latitude: 11.1075,
        longitude: 77.3398,
    },
    {
        city: "Gurgaon",
        state: "Haryana",
        latitude: 28.4595,
        longitude: 77.0266,
    },
    {
        city: "Aligarh",
        state: "Uttar Pradesh",
        latitude: 27.8974,
        longitude: 78.088,
    },
    {
        city: "Jalandhar",
        state: "Punjab",
        latitude: 31.326,
        longitude: 75.5762,
    },
    {
        city: "Bhubaneswar",
        state: "Odisha",
        latitude: 20.2961,
        longitude: 85.8245,
    },
    {
        city: "Salem",
        state: "Tamil Nadu",
        latitude: 11.6643,
        longitude: 78.146,
    },
    {
        city: "Warangal",
        state: "Telangana",
        latitude: 18.0084,
        longitude: 79.5862,
    },
    {
        city: "Mira-Bhayandar",
        state: "Maharashtra",
        latitude: 19.2952,
        longitude: 72.8542,
    },
    {
        city: "Guntur",
        state: "Andhra Pradesh",
        latitude: 16.3067,
        longitude: 80.4365,
    },
    {
        city: "Bhiwandi",
        state: "Maharashtra",
        latitude: 19.2804,
        longitude: 73.0483,
    },
    {
        city: "Saharanpur",
        state: "Uttar Pradesh",
        latitude: 29.9612,
        longitude: 77.5475,
    },
    {
        city: "Gorakhpur",
        state: "Uttar Pradesh",
        latitude: 26.7504,
        longitude: 83.3722,
    },
    {
        city: "Bikaner",
        state: "Rajasthan",
        latitude: 28.0229,
        longitude: 73.3119,
    },
    {
        city: "Amravati",
        state: "Maharashtra",
        latitude: 20.932,
        longitude: 77.7523,
    },
    {
        city: "Noida",
        state: "Uttar Pradesh",
        latitude: 28.5355,
        longitude: 77.391,
    },
    {
        city: "Jamshedpur",
        state: "Jharkhand",
        latitude: 22.8046,
        longitude: 86.2029,
    },
    {
        city: "Bhilai",
        state: "Chhattisgarh",
        latitude: 21.2092,
        longitude: 81.428,
    },
    {
        city: "Cuttack",
        state: "Odisha",
        latitude: 20.4625,
        longitude: 85.8825,
    },
    {
        city: "Firozabad",
        state: "Uttar Pradesh",
        latitude: 27.1591,
        longitude: 78.3957,
    },
    {
        city: "Kochi",
        state: "Kerala",
        latitude: 9.9312,
        longitude: 76.2673,
    },
    {
        city: "Nellore",
        state: "Andhra Pradesh",
        latitude: 14.4426,
        longitude: 79.9865,
    },
    {
        city: "Bhavnagar",
        state: "Gujarat",
        latitude: 21.755,
        longitude: 72.1446,
    },
    {
        city: "Dehradun",
        state: "Uttarakhand",
        latitude: 30.3165,
        longitude: 78.0322,
    },
    {
        city: "Durgapur",
        state: "West Bengal",
        latitude: 23.5204,
        longitude: 87.3119,
    },
    {
        city: "Asansol",
        state: "West Bengal",
        latitude: 23.6739,
        longitude: 86.9524,
    },
    {
        city: "Rourkela",
        state: "Odisha",
        latitude: 22.2604,
        longitude: 84.853,
    },
    {
        city: "Nanded",
        state: "Maharashtra",
        latitude: 19.1383,
        longitude: 77.321,
    },
    {
        city: "Kolhapur",
        state: "Maharashtra",
        latitude: 16.705,
        longitude: 74.2433,
    },
    {
        city: "Ajmer",
        state: "Rajasthan",
        latitude: 26.4499,
        longitude: 74.6399,
    },
    {
        city: "Akola",
        state: "Maharashtra",
        latitude: 20.7038,
        longitude: 77.0219,
    },
    {
        city: "Gulbarga",
        state: "Karnataka",
        latitude: 17.3296,
        longitude: 76.8343,
    },
    {
        city: "Jamnagar",
        state: "Gujarat",
        latitude: 22.4707,
        longitude: 70.0577,
    },
    {
        city: "Ujjain",
        state: "Madhya Pradesh",
        latitude: 23.1765,
        longitude: 75.7885,
    },
    {
        city: "Loni",
        state: "Uttar Pradesh",
        latitude: 28.7494,
        longitude: 77.2794,
    },
    {
        city: "Siliguri",
        state: "West Bengal",
        latitude: 26.7271,
        longitude: 88.3953,
    },
    {
        city: "Jhansi",
        state: "Uttar Pradesh",
        latitude: 25.4484,
        longitude: 78.5685,
    },
    {
        city: "Ulhasnagar",
        state: "Maharashtra",
        latitude: 19.2183,
        longitude: 73.1632,
    },
    {
        city: "Nellore",
        state: "Andhra Pradesh",
        latitude: 14.4426,
        longitude: 79.9865,
    },
    {
        city: "Sangli-Miraj & Kupwad",
        state: "Maharashtra",
        latitude: 16.8606,
        longitude: 74.5731,
    },
    {
        city: "Mangalore",
        state: "Karnataka",
        latitude: 12.9141,
        longitude: 74.856,
    },
    {
        city: "Erode",
        state: "Tamil Nadu",
        latitude: 11.341,
        longitude: 77.7172,
    },
    {
        city: "Belgaum",
        state: "Karnataka",
        latitude: 15.8497,
        longitude: 74.4977,
    },
    {
        city: "Ambattur",
        state: "Tamil Nadu",
        latitude: 13.1124,
        longitude: 80.1656,
    },
];
