module.exports.descriptors = [
    "Forest",
    "Ancient",
    "Petrified",
    "Roaring",
    "Cascade",
    "Tumbling",
    "Silent",
    "Redwood",
    "Bullfrog",
    "Maple",
    "Misty",
    "Elk",
    "Grizzly",
    "Ocean",
    "Sea",
    "Sky",
    "Dusty",
    "Diamond",
];

module.exports.places = [
    "Flats",
    "Village",
    "Canyon",
    "Pond",
    "Group Camp",
    "Horse Camp",
    "Ghost Town",
    "Camp",
    "Dispersed Camp",
    "Backcountry",
    "River",
    "Creek",
    "Creekside",
    "Bay",
    "Spring",
    "Bayshore",
    "Sands",
    "Mule Camp",
    "Hunting Camp",
    "Cliffs",
    "Hollow",
];

module.exports.descriptions = [
    "Nestled beside a serene lake, this campsite offers stunning water views and a peaceful atmosphere, perfect for fishing and kayaking.",
    "Located in a lush forest, this campsite is a nature lover's dream with hiking trails, wildlife, and starry nights by the campfire.",
    "Escape to the mountains and stay at this campsite, where you can enjoy breathtaking vistas and endless opportunities for outdoor adventure.",
    "Set along a picturesque river, this campsite is a haven for anglers, providing excellent fishing opportunities just steps from your tent.",
    "A hidden gem in the desert, this campsite boasts stunning desert landscapes, ideal for stargazing and experiencing the unique ecosystem.",
    "Enjoy beachfront camping at its finest on the sandy shores of this campsite, where sunsets and ocean waves create a tranquil ambiance.",
    "This family-friendly campsite offers a range of activities, from swimming in the natural pool to roasting marshmallows around the campfire.",
    "Immerse yourself in history at this campsite near ancient ruins, providing a one-of-a-kind cultural and outdoor experience.",
    "Discover the beauty of the Redwood forest at this campsite, where towering trees and peaceful trails invite exploration and relaxation.",
    "Escape to the high country at this campsite, where cooler temperatures and alpine scenery make for a refreshing getaway.",
    "Experience the magic of winter camping at this snow-covered campsite, complete with cross-country skiing and cozy cabins.",
    "Set beside a pristine mountain lake, this campsite offers swimming, boating, and stunning mountain views for a perfect summer retreat.",
    "Nestled in a valley, this campsite features hot springs, providing relaxation and rejuvenation after a day of hiking and exploring.",
    "Stay at this remote campsite in the wilderness, where wildlife sightings and untouched landscapes are all part of the adventure.",
    "Discover a taste of the Old West at this campsite, where you can try horseback riding and enjoy evenings under the stars.",
    "Explore the wonders of the desert at this campsite, where you can hike among cacti and watch the sunset over the sand dunes.",
    "This campsite offers the best of both worlds with a peaceful forest setting and easy access to a nearby charming mountain town.",
    "Escape to the islands at this coastal campsite, where ocean breezes and water sports create an island paradise experience.",
    "Immerse yourself in fall foliage at this campsite, where vibrant colors and crisp air make for a memorable autumn getaway.",
    "Stay at this campsite on a working farm, where you can enjoy farm-to-table meals and learn about sustainable agriculture.",
    "Set in a canyon, this campsite offers dramatic rock formations, hiking trails, and the soothing sound of a flowing river.",
    "This campsite is a birdwatcher's delight, with diverse avian species and tranquil surroundings for nature enthusiasts.",
    "Escape to a lakeside campsite where you can swim, paddleboard, and soak up the sun on a private beach.",
    "Experience the charm of a rustic campsite, complete with log cabins and campfires for a cozy and nostalgic stay.",
    "Stay in a treehouse at this unique campsite, surrounded by the canopy and providing a one-of-a-kind wilderness experience.",
    "Explore the wonders of the Everglades at this campsite, where airboat tours and wildlife encounters are just a step away.",
    "This campsite offers access to a pristine wilderness area, perfect for backpackers seeking solitude and scenic beauty.",
    "Unplug and unwind at this campsite in a secluded forest, where the absence of technology enhances the natural experience.",
    "Set on the edge of a crystal-clear lake, this campsite is a paradise for water sports enthusiasts and swimmers alike.",
    "Enjoy riverside camping at this tranquil spot, where you can listen to the soothing sounds of the river from your tent.",
    "Experience the thrill of glamping at this luxury campsite, offering comfortable amenities in a stunning natural setting.",
    "This campsite is a mountain climber's dream, providing access to challenging peaks and breathtaking alpine vistas.",
    "Stay at this beachfront campsite, where you can surf, build sandcastles, and enjoy evening bonfires by the sea.",
    "Nestled in a meadow, this campsite offers peaceful surroundings and easy access to hiking trails and wildlife viewing.",
    "Camp beneath towering waterfalls at this scenic site, where the mist and roar of the falls create a unique camping experience.",
    "Explore the beauty of the Badlands at this campsite, with rugged landscapes and opportunities for fossil hunting.",
    "This campsite is perfect for wine lovers, with nearby vineyards and wine tastings in a picturesque setting.",
    "Stay at this campsite in the heart of a national park, where wildlife encounters and pristine nature await.",
    "Escape to a remote island campsite, where you can enjoy solitude, beachcombing, and stunning sunrises.",
    "Experience the thrill of winter camping at this snowy wonderland, with cross-country skiing and cozy cabins.",
    "This campsite is a fisherman's paradise, offering excellent angling opportunities in a secluded mountain lake.",
    "Camp in a lush rainforest, where exotic flora and fauna create a magical atmosphere for nature enthusiasts.",
    "Stay at this campsite on the shores of a serene lake, where you can fish, swim, and paddle to your heart's content.",
    "Immerse yourself in Native American culture at this campsite, offering traditional storytelling and arts and crafts.",
    "Set in a canyon, this campsite offers epic rock climbing routes and breathtaking vistas from the top.",
    "Discover the beauty of the Smoky Mountains at this campsite, where hiking trails and wildlife abound.",
    "This campsite is a photographer's dream, with stunning sunsets, wildlife, and landscapes waiting to be captured.",
    "Stay at this campsite on a working ranch, where you can participate in cattle drives and enjoy cowboy-style cookouts.",
    "Camp in the shadow of a volcano at this unique site, with opportunities for lava field exploration and stargazing.",
    "Experience the magic of bioluminescent waters at this coastal campsite, with kayak tours and mesmerizing night displays.",
    "Nestled in a forested canyon, this campsite offers tranquility and easy access to hiking trails and natural wonders.",
    "Camp on the edge of a pristine alpine lake, where you can fish, canoe, and enjoy the beauty of the surrounding peaks.",
];
